import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sign in to Outlook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Any other meta tags or head elements you need */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
